#  NOTE: The following parameters are set by automation
#
#  cluster_domain: <STACK_NAME>.local
#  cluster_name: <STACK_NAME>
#  openldap_domain: <STACK_NAME>.local
#  openstack_compute_count: '<COMPUTE_NODES_COUNT>'
#  openstack_network_engine: From STACK_INSTALL. If STACK_INSTALL includes opencontrail, then it'll be set to opencontrail
#  (openstack|kubernetes|cicd|stacklight|opencontrail)_enabled: From STACK_INSTALL.
#  platform: From STACK_INSTALL. Either openstack or kubernetes
#  public_host: From STACK_INSTALL. Either ${_param:openstack_proxy_address} for OS or ${_param:infra_config_address} for K8S
default_context:
  openssh_groups: "qa_scale,oscore_devops,networking,tcpcloud,stacklight,k8s_team"
  cookiecutter_template_url: https://gerrit.mcp.mirantis.net/mk/cookiecutter-templates.git
  cookiecutter_template_branch: ''
  shared_reclass_url: https://gerrit.mcp.mirantis.net/salt-models/reclass-system.git
  shared_reclass_branch: ''
  mcp_common_scripts_branch: ''
  bmk_enabled: 'False'
  ceph_enabled: 'False'
  cicd_control_node01_address: 10.11.0.91
  cicd_control_node01_hostname: cid01
  cicd_control_node02_address: 10.11.0.92
  cicd_control_node02_hostname: cid02
  cicd_control_node03_address: 10.11.0.93
  cicd_control_node03_hostname: cid03
  cicd_control_vip_address:   10.11.0.90
  cicd_control_vip_hostname: cid
  cicd_private_key: |-
    -----BEGIN RSA PRIVATE KEY-----
    MIIEogIBAAKCAQEAqdHr4zmivHPEimCuK9vtATe4PvGEr0Np/JxYDlEQsr5Cajh4
    tajxmZrjdAnJWFXVbmYl21sN1cUW0ltxB+9+lc4GNVNCZqE4kmpsyx2lrF7xCFvF
    Qou26JYud/UCT9IpCYgWjQIGSC8gq1TzfgOpn6rWnLNSl3WdM5TKtQT7RXIkdSUw
    kXFbObz9lsM+ULWNozCId2osJHj4zE0D3H5odU5DpcWLuSG0MmdxtWoQNJjSiPWt
    HbRdvNmr/xeqcAfzdUdZxGf/VbXDdiNZn9TVv7UxxBHE812KNUf/Cvb5agDfEL7x
    i2bWXbhr4jVTaDVr6MWl8Q7fAj79gdjQnUBWaQIDAQABAoIBAFU3kU6yIna9BViH
    UX+S2ijtRBjZ68JjavEnp4xvo5h+nydcdT57q9lv/0nAi3g3gmXm/oJH+/ZU87HV
    zy+zP+t+umDSChUkPBZFL5jxpKyN7BhMrP1KzRuEGYd6vJE/nfY5g095P5vDgnpX
    o+SNg/YqrY1u8zgr/hnfRaV2/XyIDEEcQXTHseWTnnMQnULFU88xL8yq8ACT5GhK
    7A9m5ukfcU6d/fs/psz5Yqw5IQsWbv1yJ3/FKufPHlo2Nzh3/3eDAZUXvaBgf1so
    FWFpHtkry3OXOGaZ98HgF9hL0twS0pzMvuypdGUQAt6nyB1N5re4LK/MAOddqwEc
    1+NQzfECgYEA2ryEf0GLJdtiYs3F4HbwTwJVIXdyWv7kjYGeMkutzzAjXl6wx8aq
    kfqLJ7x7UkR5unZ1ajEbKBciAlSuFA+Gikn6a4Lv8h87aSnHpPd/2VSitRlI/gW7
    w4U4CL3Br1JyonU5WA7VYfTow7KnHBhdwm27RMA9uosyIpveQRpqSG0CgYEAxsAS
    wCQKrhuPq2YtGtFR7K4BL+N+0E1Vq6h49u1ukcgUe0GHVD3VzBypNCv7rWEVHzAg
    biCVi7PCjzZYW4fYZmzVD4JbFLVGOUu7aJwLaE4wDe72DNr6YZhcS+Ta98BP+x0q
    Wt34JNPDabRPfhXfhiCqnWjjod+4Zqx4VJVNgG0CgYB5EXL8xJhyAbW5Hk/x56Mm
    +BGKjoR7HS3/rMiU6hJv5SMObrbGPI3YcqZm/gn8BO6jaEGg30E6tWMbiyc270j2
    be/vZe/NQcAuevOHuX3IGvJb7nzaLO46UBgtrmnv0mCkzuFIfh1ZNKdI+i9Ie6wZ
    m4bVjNod0EGVqlQgELDXGQKBgB+NNmzSS++/6FrpaZesSzkrlnynvOYMoOETacCp
    iLgT70xx5q308w/oLORfZyDrHJNK7JsPCS6YZvadRgGh2zTHajuAEj2DWZaW8zV0
    MEtqvi44FU+NI9qCeYSC3FAgc5IF20d5nX8bLxaEzWnSxx1f6jX7BMgZ4AhMsP2c
    hiUxAoGAFaxn+t9blIjqUiuh0smSYFhLBVPZveYHQDmQYERjktptBd3X95fGnSKh
    iDe2iPGyud2+Yu4X/VjHLh/MRru+ZXvPXw1XwEqX93q8a1n283ul0Rl9+KKKOVHR
    eecTjI/BfXBf33mPRKny3xuHw6uwta2T3OXky9IhqYS1kkHiZWA=
    -----END RSA PRIVATE KEY-----
  cicd_public_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCp0evjOaK8c8SKYK4r2+0BN7g+8YSvQ2n8nFgOURCyvkJqOHi1qPGZmuN0CclYVdVuZiXbWw3VxRbSW3EH736VzgY1U0JmoTiSamzLHaWsXvEIW8VCi7boli539QJP0ikJiBaNAgZILyCrVPN+A6mfqtacs1KXdZ0zlMq1BPtFciR1JTCRcVs5vP2Wwz5QtY2jMIh3aiwkePjMTQPcfmh1TkOlxYu5IbQyZ3G1ahA0mNKI9a0dtF282av/F6pwB/N1R1nEZ/9VtcN2I1mf1NW/tTHEEcTzXYo1R/8K9vlqAN8QvvGLZtZduGviNVNoNWvoxaXxDt8CPv2B2NCdQFZp
  compute_bond_mode: active-backup
  compute_primary_first_nic: ens4
  compute_primary_second_nic: ens5
  context_seed: tY2TsXCZW4Z80Tes4iIT1qgkc2lIsEBTytnS7HmVFCKQAeqLnfNqIeK4vCyAD02j
  control_network_netmask: 255.255.0.0
  control_network_subnet: 10.11.0.0/16
  control_vlan: '10'
  deploy_network_gateway: 10.10.0.1
  deploy_network_netmask: 255.255.0.0
  deploy_network_subnet: 10.10.0.0/24
  deployment_type: physical
  dns_server01: 172.18.176.6
  dns_server02: 172.17.44.91
  infra_deploy_nic: ens3
  infra_kvm01_control_address: 10.11.0.241
  infra_kvm01_deploy_address: 10.10.0.241
  infra_kvm01_hostname: kvm01
  infra_kvm02_control_address: 10.11.0.242
  infra_kvm02_deploy_address: 10.10.0.242
  infra_kvm02_hostname: kvm02
  infra_kvm03_control_address: 10.11.0.243
  infra_kvm03_deploy_address: 10.10.0.243
  infra_kvm03_hostname: kvm03
  infra_kvm_vip_address: 10.11.0.240
  infra_primary_first_nic: ens4
  infra_primary_second_nic: ens5
  local_repositories: 'False'
  maas_deploy_address: 10.10.0.15
  mcp_version: proposed
  offline_deployment: 'False'
  opencontrail_analytics_address: 10.11.0.227
  opencontrail_analytics_hostname: nal
  opencontrail_analytics_node01_address: 10.11.0.228
  opencontrail_analytics_node01_hostname: nal01
  opencontrail_analytics_node02_address: 10.11.0.229
  opencontrail_analytics_node02_hostname: nal02
  opencontrail_analytics_node03_address: 10.11.0.230
  opencontrail_analytics_node03_hostname: nal03
  opencontrail_compute_iface_mask: '24'
  opencontrail_control_address: 10.11.0.223
  opencontrail_control_hostname: ntw
  opencontrail_control_node01_address: 10.11.0.224
  opencontrail_control_node01_hostname: ntw01
  opencontrail_control_node02_address: 10.11.0.225
  opencontrail_control_node02_hostname: ntw02
  opencontrail_control_node03_address: 10.11.0.226
  opencontrail_control_node03_hostname: ntw03
  opencontrail_enabled: 'True'
  opencontrail_router01_address: 10.11.0.131
  opencontrail_router01_hostname: vmx01
  openldap_enabled: 'True'
  openldap_organisation: ${_param:cluster_name}
  openstack_benchmark_node01_address: 10.11.0.95
  openstack_benchmark_node01_hostname: bmk01
  openstack_compute_rack01_hostname: cmp
  compute_padding_with_zeros: 'False'
  openstack_compute_rack01_single_subnet: 10.11.1
  openstack_compute_rack01_tenant_subnet: 10.12.2
  openstack_control_address: 10.11.0.10
  openstack_control_hostname: ctl
  openstack_control_node01_address: 10.11.0.11
  openstack_control_node01_hostname: ctl01
  openstack_control_node02_address: 10.11.0.12
  openstack_control_node02_hostname: ctl02
  openstack_control_node03_address: 10.11.0.13
  openstack_control_node03_hostname: ctl03
  openstack_database_address: 10.11.0.50
  openstack_database_hostname: dbs
  openstack_database_node01_address: 10.11.0.51
  openstack_database_node01_hostname: dbs01
  openstack_database_node02_address: 10.11.0.52
  openstack_database_node02_hostname: dbs02
  openstack_database_node03_address: 10.11.0.53
  openstack_database_node03_hostname: dbs03
  openstack_gateway_node01_address: 10.11.0.224
  openstack_gateway_node01_hostname: gtw01
  openstack_gateway_node01_tenant_address: 10.12.0.224
  openstack_gateway_node02_address: 10.11.0.225
  openstack_gateway_node02_hostname: gtw02
  openstack_gateway_node02_tenant_address: 10.12.0.225
  openstack_gateway_node03_address: 10.11.0.226
  openstack_gateway_node03_hostname: gtw03
  openstack_gateway_node03_tenant_address: 10.12.0.226
  openstack_message_queue_address: 10.11.0.40
  openstack_message_queue_hostname: msg
  openstack_message_queue_node01_address: 10.11.0.41
  openstack_message_queue_node01_hostname: msg01
  openstack_message_queue_node02_address: 10.11.0.42
  openstack_message_queue_node02_hostname: msg02
  openstack_message_queue_node03_address: 10.11.0.43
  openstack_message_queue_node03_hostname: msg03
  openstack_network_engine: ovs
  openstack_neutron_qos: 'False'
  openstack_neutron_vlan_aware_vms: 'False'
  openstack_nfv_dpdk_enabled: 'False'
  openstack_nfv_sriov_enabled: 'False'
  openstack_nova_compute_nfv_req_enabled: 'False'
  openstack_ovs_dvr_enabled: 'False'
  openstack_ovs_encapsulation_type: vxlan
  openstack_proxy_address: 10.11.0.80
  openstack_proxy_hostname: prx
  openstack_proxy_node01_address: 10.11.0.81
  openstack_proxy_node01_hostname: prx01
  openstack_proxy_node02_address: 10.11.0.82
  openstack_proxy_node02_hostname: prx02
  openstack_upgrade_node01_address: 10.11.0.19
  openstack_version: pike
  k8s_keepalived_vip_vrid: 69
  k8s_api_insecure_bind: 'True'
  kubernetes_compute_node01_address: 10.11.0.101
  kubernetes_compute_node01_deploy_address: 10.10.0.101
  kubernetes_compute_node01_hostname: cmp01
  kubernetes_compute_node02_address: 10.11.0.102
  kubernetes_compute_node02_deploy_address: 10.10.0.102
  kubernetes_compute_node02_hostname: cmp02
  kubernetes_compute_node02_deploy_address: 10.10.0.103
  kubernetes_compute_node02_hostname: cmp03
  kubernetes_control_address: 10.11.0.10
  kubernetes_control_node01_address: 10.11.0.11
  kubernetes_control_node01_deploy_address: 10.10.0.11
  kubernetes_control_node01_hostname: ctl01
  kubernetes_control_node02_address: 10.11.0.12
  kubernetes_control_node02_deploy_address: 10.10.0.12
  kubernetes_control_node02_hostname: ctl02
  kubernetes_control_node03_address: 10.11.0.13
  kubernetes_control_node03_deploy_address: 10.10.0.13
  kubernetes_control_node03_hostname: ctl03
  kubernetes_externaldns_enabled: 'False'
  kubernetes_keepalived_vip_interface: ens4
  kubernetes_network_calico_enabled: True
  kubernetes_virtlet_enabled: 'False'
  oss_enabled: 'False'
  oss_notification_app_id: '24'
  oss_notification_sender_password: password
  oss_notification_smtp_port: '587'
  oss_notification_webhook_login_id: '13'
  publication_method: email
  reclass_repository: https://github.com/Mirantis/mk-lab-salt-model.git
  salt_api_password: AiTEn1h1GqQRw9lsn7Iv5Pydrlu1qjWA
  salt_api_password_hash: $6$gYsIBmqk$Q5hX10wZwccUY.8hFxiiWVxPmh3NDl/QFQedQHSvhh7hN8vBQ9Lwfvd0x1E7TUCEGybyJFPXRHL/phM2LHyZC0
  salt_master_address: 10.11.0.15
  salt_master_hostname: cfg01
  salt_master_management_address: 10.10.0.15
  stacklight_log_address: 10.11.0.60
  stacklight_log_hostname: log
  stacklight_log_node01_address: 10.11.0.61
  stacklight_log_node01_hostname: log01
  stacklight_log_node02_address: 10.11.0.62
  stacklight_log_node02_hostname: log02
  stacklight_log_node03_address: 10.11.0.63
  stacklight_log_node03_hostname: log03
  stacklight_long_term_storage_type: prometheus
  fluentd_enabled: 'True'
  stacklight_monitor_address: 10.11.0.70
  stacklight_monitor_hostname: mon
  stacklight_monitor_node01_address: 10.11.0.71
  stacklight_monitor_node01_hostname: mon01
  stacklight_monitor_node02_address: 10.11.0.72
  stacklight_monitor_node02_hostname: mon02
  stacklight_monitor_node03_address: 10.11.0.73
  stacklight_monitor_node03_hostname: mon03
  stacklight_notification_address: alerts@localhost
  stacklight_notification_smtp_host: 127.0.0.1
  stacklight_telemetry_address: 10.11.0.85
  stacklight_telemetry_hostname: mtr
  stacklight_telemetry_node01_address: 10.11.0.86
  stacklight_telemetry_node01_hostname: mtr01
  stacklight_telemetry_node02_address: 10.11.0.87
  stacklight_telemetry_node02_hostname: mtr02
  stacklight_telemetry_node03_address: 10.11.0.88
  stacklight_telemetry_node03_hostname: mtr03
  stacklight_version: '2'
  tenant_network_gateway: 10.12.0.1
  tenant_network_netmask: 255.255.0.0
  tenant_network_subnet: 10.12.0.0/16
  tenant_vlan: '20'
  upstream_proxy_enabled: 'False'
